name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup
      run: brew install ragel boost multimarkdown hg ninja capnp google-sparsehash libressl
    - name: Configure
      run: ./configure && ninja Frameworks/encoding/src/frequencies.capnp.h
    - name: Build
      run: ninja TextMate
